#!/usr/bin/env bash
# Initialize the counter
n=1
# Iterate the loop for 10 times
while [ $n -le 10 ]
do
    # Print the value of n in each iteration
    echo "Best School"
    # Increment the value of n by 1
    (( n++ ))
done
