#!/usr/bin/env bash
#Write a Bash script that displays Best School 10 times.
#Write a Bash script that displays Best School 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.
n=1
while [ $n -le 10 ]
do
	((n++))
	if [ $n == 10 ]
	then
		echo "hi"
	continue
	fi
	echo "Best School"
done
