#!/usr/bin/env bash
#Write a Bash script that gives you information about the school file.
echo "school"
read -r file
if [ -e "$file" ]
then
echo "School file exists"
  if [ -f "$file" ]
  then
   	echo "school is a regular file"
		if [ -s "file" ]
		then
			echo "school file is not  empty"
		else
			echo "school file is empty"
		fi
    fi
else
  echo "school file does not exit"
fi
