#!/usr/bin/env bash 
#Creates the file /var/run/myscript.pid containing its PID
	echo $$ > /var/run/myscript.pid
	trap " echo 'I hate the kill command' " SIGTERM
	trap " echo 'Y U no love me?!' " SIGINT
	trap " rm /var/run/myscript.pid " SIGQUIT SIGTERM EXIT
while :
do
	echo " To infinity and beyond "
	sleep 2
done
