#!/usr/bin/env bash
#Manage my process
if [ $(("$#"==1)) ]
then
	if [ "$1" == "start" ]
	then
		./manage_my_process &
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process started"
	elif [ "$1" == "stop" ]
	then
		pkill -f ./manage_my_process
		pkill -15 $(cat /var/run/my_process.pid)
		rm -rf /var/run/my_process.pid
		echo "manage_my_process stopped"
	elif [ "$1" == "restart" ]
	then
		pkill -f ./manage_my_process
		rm -rf /var/run/my_process.pid
		./manage_my_process &
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process restarted"

	else
		echo "Usage: manage_my_process {start|stop|restart}"
	fi
fi

